<?php
/**
 * Load html for meta field
 *
 * This file is used to add meta field in notification cpt.
 *
 * @link       https://makewebbetter.com/
 * @since      1.0.0
 *
 * @package    Mwb_Web_Notifications_For_Wp
 * @subpackage Mwb_Web_Notifications_For_Wp/templates/backend
 */

?>
<div id="mwb-mwnfw-notification__modal" class="mwb-mwnfw-notification__type-modal" style="display: none;" title="<?php esc_html_e( 'Choose Notification Type', 'mwb-web-notifications-for-wp' ); ?>" >
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=propensity' ) ); ?>" id="mwb-mwnfw-notification__type-propensity" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-propensity"><span class="mwb-mwnfw__modal-content"><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/Propensity.svg" alt="propensity Modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Propensity', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=reward' ) ); ?>" id="mwb-mwnfw-notification__type-reward" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-reward"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/Reward.svg" alt="reward modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Reward', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=success' ) ); ?>" id="mwb-mwnfw-notification__type-success" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-success"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/success.svg" alt="success modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Success', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=invite' ) ); ?>" id="mwb-mwnfw-notification__type-invite" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-invite"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/Invite.svg" alt="Invite modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Invite', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=offer' ) ); ?>" id="mwb-mwnfw-notification__type-offer" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-offer"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/Offer.svg" alt="offer modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Offer', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=promotion' ) ); ?>" id="mwb-mwnfw-notification__type-promotion" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-promotion"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/Promotion.svg" alt="promotion modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Promotion', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=feedback' ) ); ?>" id="mwb-mwnfw-notification__type-feedback" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-feedback"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/Feedback.svg" alt="feedback modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Feedback', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=sticky-nav' ) ); ?>" id="mwb-mwnfw-notification__type-sticky-nav" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-sticky-nav"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/sticky_bar.svg" alt="Nav bar modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Sticky Nav Bar', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
		<a href="<?php echo esc_attr( admin_url( 'post-new.php?post_type=mwb_notification&mwnfw_type=custom' ) ); ?>" id="mwb-mwnfw-notification__type-custom" class="mwb-mwnfw-notification__type mwb-mwnfw-notification__type-custom"><span class="mwb-mwnfw__modal-content" ><img class="svg" src="<?php echo esc_html( MWB_WEB_NOTIFICATIONS_FOR_WP_DIR_URL ); ?>admin/image/icons/custom_notification.svg" alt="Custom modal image"><span class="mwb-mwnfw__modal-text"><?php esc_html_e( 'Custom', 'mwb-web-notifications-for-wp' ); ?></span></span></a>
</div>
